// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5kLcYqaf5SHvqf4FEp8XEmUPaTAGqHA',
    appId: '1:182869968469:web:e9c18acee7b0662ada36dc',
    messagingSenderId: '182869968469',
    projectId: 'economics-learner',
    authDomain: 'economics-learner.firebaseapp.com',
    storageBucket: 'economics-learner.firebasestorage.app',
    measurementId: 'G-H5148B4R0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_eHWMcFSU1mFFGsnBklRK0e5e3-ddfGg',
    appId: '1:182869968469:android:c300f67d2af93099da36dc',
    messagingSenderId: '182869968469',
    projectId: 'economics-learner',
    storageBucket: 'economics-learner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlsgGygHxEdVpRh5eCQB7GEYKRUjbxAbg',
    appId: '1:182869968469:ios:f04322fa84ebe228da36dc',
    messagingSenderId: '182869968469',
    projectId: 'economics-learner',
    storageBucket: 'economics-learner.firebasestorage.app',
    iosBundleId: 'com.example.economicsLearner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlsgGygHxEdVpRh5eCQB7GEYKRUjbxAbg',
    appId: '1:182869968469:ios:f04322fa84ebe228da36dc',
    messagingSenderId: '182869968469',
    projectId: 'economics-learner',
    storageBucket: 'economics-learner.firebasestorage.app',
    iosBundleId: 'com.example.economicsLearner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj5kLcYqaf5SHvqf4FEp8XEmUPaTAGqHA',
    appId: '1:182869968469:web:cf2a7c801fe52bcdda36dc',
    messagingSenderId: '182869968469',
    projectId: 'economics-learner',
    authDomain: 'economics-learner.firebaseapp.com',
    storageBucket: 'economics-learner.firebasestorage.app',
    measurementId: 'G-GSBX2T107J',
  );
}
